"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Блок определения корневой папки проекта.
# BASE_DIR используется для построения путей к базе данных, статике и медиафайлам.
BASE_DIR = Path(__file__).resolve().parent.parent

# Блок базовых параметров безопасности Django.
# SECRET_KEY подписывает cookie и токены; в промышленной среде его нужно хранить в переменной окружения.
SECRET_KEY = 'django-insecure-4ju2n@$f9d0c=h)_g0lbb%k9&@rf(xa$d$g$&5ri$uf)*gev^4'

# DEBUG=True удобен для лабораторного запуска, но раскрывает диагностическую информацию при ошибках.
DEBUG = True

# Блок доверенных доменов Replit.
# Домены берутся из REPLIT_DOMAINS, чтобы Django принимал запросы с адресов текущего контейнера.
ALLOWED_HOSTS = os.environ["REPLIT_DOMAINS"].split(',')
CSRF_TRUSTED_ORIGINS = [
    "https://" + domain for domain in os.environ["REPLIT_DOMAINS"].split(',')
]

# Блок подключенных приложений.
# Стандартные приложения Django обеспечивают админку, сессии, авторизацию и статику.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'risk_app',
]

# Блок middleware-цепочки.
# Каждый middleware обрабатывает запрос или ответ: безопасность, сессии, метрики и авторизация.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'risk_app.metrics.PrometheusMetricsMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

# Блок защиты от clickjacking для деплоя.
# В Replit Web View защита отключается в разработке, потому что просмотр использует iframe.
if ("REPLIT_DEPLOYMENT" in os.environ):
    MIDDLEWARE.append('django.middleware.clickjacking.XFrameOptionsMiddleware')

# Блок корневой маршрутизации.
ROOT_URLCONF = 'django_project.urls'

# Блок шаблонов.
# APP_DIRS=True разрешает Django искать HTML-шаблоны внутри risk_app/templates.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Блок WSGI-приложения.
# WSGI используется сервером для запуска Django-приложения внутри контейнера.
WSGI_APPLICATION = 'django_project.wsgi.application'

# Блок базы данных.
# В текущей конфигурации Django использует SQLite-файл внутри папки проекта.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Блок проверки сложности паролей Django.
# Валидаторы применяются при использовании стандартной системы пользователей Django.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Блок локализации и часового пояса.
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Блок статических файлов.
# STATIC_ROOT нужен для collectstatic при запуске контейнера.
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Блок типа первичных ключей моделей.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Блок медиафайлов.
# Сюда сохраняются графики img1.jpeg и img2.jpeg, создаваемые в risk_app/views.py.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Блок приема запросов с любых хостов в учебной среде.
ALLOWED_HOSTS = ['*']

# Блок работы за reverse proxy.
# Заголовок X-Forwarded-Proto сообщает Django, что внешний запрос был HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
